### ISSUE TITLE
Bug: Filtering Lists

### ISSUE THREAD

**Issue by mtettke123** [go-vikunja/frontend#69]
Using the "filter" button in list view, I can filter "assignees" (small bug: When selecting a person, you can see the selected person a couple of millisecons, then the field is empty again, but the filter works).

Using the "new saved filter" setting in namespaces/lists, filtering with an assignee always returns an empty list.

Small workflow improvement: it would be great if filters in list view could be saved ("save this filter").

**Comment by kolaente** [comment]
Can you reproduce this on [try](https://try.vikunja,.io)?

**Comment by mtettke123** [comment]
Well, surprinsingly no. Filtering works here (but I'm using unstable, shouldn't this be the same?). The small bug (selecting a person that disappears is strange in try, too: Selecting "demo" as user yields to:
![grafik](https://user-images.githubusercontent.com/82048170/182862514-848d892a-00d5-46a6-895d-fc059c702ec8.png)

**Comment by kolaente** [comment]
> Well, surprinsingly no. Filtering works here

Then it's probably already fixed in unstable.

> but I'm using unstable, shouldn't this be the same?

It should, when did you last upgrade?

> The small bug (selecting a person that disappears is strange in try, too: Selecting "demo" as user yields to:

That sounds like another bug. I'll take a look.

**Comment by mtettke123** [comment]
Filtering seems to be solved. Just updated. works.

The small bug is still there (in my installation: selected person disappers like if no one is selected, but filter works)...

**Comment by glungtung** [comment]
I confirm
Person disappears immediatly after selection in Assignees
But filter can be created and is working

**Comment by kolaente** [comment]
The cause of this problem is a little complicated and has two parts.

In the frontend, the bug occurs because the filter value changes after a user was selected. This triggers a rebuild of all filter values which for the assignee filter means a search request to get the full name etc of the user. BUT the assignee filter only stores user ids and the user search endpoint does not handle those (to prevent usernames leaking by just increasing the id). Therefore, the search returns no results and the user disappears. The filter component does this to show the correct values if the filter changed from the outside (aka was just loaded).
This can be fixed with a check if there's already data loaded and not loading it if that's the case. Still not ideal because then it won't update if the filter is changed from the outside again after loading it but we're not doing that at the moment.

The other problem is the mentioned filter search: Because we can't lookup user IDs we should ideally save usernames. They are unique and relatively un-guessable (no enumeration possible). If we save usernames instead of IDs we'll need to change the filter logic so that it is able to search by username instead of ID. Possible. but a breaking change.

**Comment by ToniMurcia** [comment]
Filtering by asignee works great in list view but not in kanban, it always returns an empty list.

**Comment by ToniMurcia** [comment]
Do you mean "Filters are not supported for kanban" only for assigne field? Because the rest of fields work great: labels, priority, progress, etc.

**Comment by kolaente** [comment]
I mean you can't filter by Kanban buckets or view a saved filter in Kanban view.

**Comment by kolaente** [comment]
This has been fixed in the meantime.
